sude: required
services:
  - docker

before_install: 
  - docker build -t dockerswap9/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dockerswap9/react-test CI=true npm test -- --coverage

after_success:
  - docker build -t dockerswap9/multi-client ./client
  - docker build -t dockerswap9/multi-nginx ./nginx
  - docker build -t dockerswap9/multi-server ./server
  - docker build -t dockerswap9/multi-worker ./worker
  # login docker at travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push it to dockerhub
  - docker push dockerswap9/multi-client
  - docker push dockerswap9/multi-nginx
  - docker push dockerswap9/multi-server
  - docker push dockerswap9/multi-worker

